name: CI AuthService

on:
  pull_request:
    branches-ignore:
      - '**/test'  # Ignore branches específicas se necessário
  push:
    branches:
      - main
      - dev
      - feature/**
      - fix/**
      - devops

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run tests
      - name: Run tests
        run: mvn test

  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Build the application
      - name: Build
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Garantir que ambos jobs (build e test) tenham sucesso

    steps:
      # Deploy application
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.DEPLOY_AUTH_PROD }}
        run: |
          echo "Deploying to Production"
          curl "$deploy_url"

      # Deploy application to Staging (Development)
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/dev'
        env:
          deploy_dev_url: ${{ secrets.DEPLOY_AUTH_DEV }}
        run: |
          echo "Deploying to Staging"
          curl "$deploy_dev_url"
